---
title: "About this course"
---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

---



---

### Course overview

The overall aim of this course is to give an overview of concepts and methods for estimating causal effects of treatments on time-to-event outcomes. Topics covered will include time-dependent treatments and confounding, inverse probability of treatment weighting and marginal structural models, g-formula, censoring-and-weighting approaches and competing risks. 

The course will combine lectures and computer sessions. There will be an emphasis on practical implementation, and all analyses and exercises will be performed using R. At the end of the course, participants should be equipped to perform analyses to address questions about causal effects of treatments on their own data.
---

### Content

Over the recent decades we have seen major developments in methods for causal inference using observational data, but the practical application of these methods can be challenging, especially in the context of survival and other time-to-event outcomes.

This course will cover methods for confounding adjustment with time-to-event outcomes, including inverse probability of treatment weighting and marginal structural models, g-formula, and censoring-and-weighting approaches. We will cover settings in which the treatment of interest is given at a single time point, as well as more complex situations in which interest lies in time-varying treatments. Focus will be on the choice of appropriate estimands and links will be made to the target trial framework. Most of the emphasis will be on simple survival outcomes, but extensions to competing risks will also be discussed. Much of the material will be presented with medical and epidemiological applications in mind, but the methods are equally relevant in other areas, such as demography, social sciences and economics.

---

### Who is this course for?

This course is aimed at researchers and students in biostatistics, statistics, epidemiology and related fields. Some knowledge of methods for survival analysis will be assumed, such as experience with estimation of survival curves using the Kaplan-Meier estimator and fitting regression models to time-to-event data. Participants should have some prior experience of using R, though not necessarily in the context of time-to-event analysis or causal inference. Knowledge of causal concepts would be beneficial, but we will not assume this. 

---

###  Schedule

All times are in CET.

**Day 1**

|Time                 |Topic                                                                                         |Tutor                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|09:15 - 09:30         |Welcome and introductions                                      |                               |

**Part 1: Introduction and estimation of the effects of point treatments on survival**

|                 |                                                                                         |                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|09:30 - 10:15        |Lecture: Causal estimands for time-to-event outcomes and identification using observational data | Jon Michael Gran                         |                       |
|10:30 - 11:15        |Lecture: Weighting and standardisation for point treatments | Ruth Keogh                         |
|11:15 - 12:45        |R practical: Weighting and standardisation for point treatments | Ruth Keogh                           |

**Part 2: Extensions to time-dependent treatment strategies**

|                 |                                                                                         |                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|13:45 - 14:30        |Lecture: Extensions to time-dependent treatment strategies, and the challenge of time-dependent confounding |  Jon Michael Gran                        |                       |
|14:30 - 16:00        |R practical: Artificial censoring and censor weighting | Jon Michael Gran                         |

**Day 2**
 
**Part 3: Further methods for time-dependent treatment strategies**

|                 |                                                                                         |                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|09:30 - 10:15        |Lecture: The sequential trials approach and marginal structural models | Ruth Keogh                         |                       |
|10:30 - 11:15        |Lecture: The g-formula |Ruth Keogh                          |
|11:15 - 12:45        |R practical: Estimation using the more advanced methods |  Ruth Keogh                        |

**Part 4: Extensions to more complex time-to-event outcomes**

|                 |                                                                                         |                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|13:45 - 14:30        |Lecture: Estimating causal effects on time-to-event outcomes under competing risks |Jon Michael Gran                          |                       |
|14:30 - 16:00        |R practical: Extensions of previously introduced methods to competing risks | Jon Michael Gran                          |


---

### Contact

For questions about the course or your registration please contact the course organisers by email on j.m.gran "at" medisin.uio.no or ruth.keogh "at" lshtm.ac.uk.


</br>
