---
title: "Causal inference for time-to-event outcomes -- with practical applications in R"
subtitle: "2-day, online ISCB course in biostatistics (8–9 April 2024)"
---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

---

### Welcome

Welcome to the webpages for this online ISCB course in biostatistics on causal inference for time-to-event outcome with practical applications in R.

To register for the course, follow the instruction at ... 

Note that there is a limit to the number of participants to the course and that registration will be closed when this limit is reached.

All teaching resources will be put out on this webpage in due time before the beginning of the course. Information about how to access these files will sent out to registrered participants together with Zoom links for the lectures and R practicals.

More details about the course can be found [here](about.html).

---

###  Schedule

**Day 1**

|Time                 |Topic                                                                                         |Tutor                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|09:15 - 09:30         |Welcome and introductions                                      |                               |

**Part 1: Introduction and estimation of the effects of point treatments on survival**

|                 |                                                                                         |                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|09:30 - 10:15        |Lecture: Causal estimands for time-to-event outcomes and identification using observational data | Jon Michael Gran                         |                       |
|10:30 - 11:15        |Lecture: Weighting and standardisation for point treatments | Ruth Keogh                         |
|11:15 - 12:45        |R practical: Weighting and standardisation for point treatments | Ruth Keogh                           |

**Part 2: Extensions to time-dependent treatment strategies**

|                 |                                                                                         |                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|13:45 - 14:30        |Lecture: Extensions to time-dependent treatment strategies, and the challenge of time-dependent confounding |  Jon Michael Gran                        |                       |
|14:30 - 16:00        |R practical: Artificial censoring and censor weighting | Jon Michael Gran                         |

**Day 2**
 
**Part 3: Further methods for time-dependent treatment strategies**

|                 |                                                                                         |                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|09:30 - 10:15        |Lecture: The sequential trials approach and marginal structural models | Ruth Keogh                         |                       |
|10:30 - 11:15        |Lecture: The g-formula |Ruth Keogh                          |
|11:15 - 12:45        |R practical: Estimation using the more advanced methods |  Ruth Keogh                        |

**Part 4: Extensions to more complex time-to-event outcomes**

|                 |                                                                                         |                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|13:45 - 14:30        |Lecture: Estimating causal effects on time-to-event outcomes under competing risks |Jon Michael Gran                          |                       |
|14:30 - 16:00        |R practical: Extensions of previously introduced methods to competing risks | Jon Michael Gran                          |

</br>
