---
title: "Preparations"
---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

---

Before participating the course please make sure that you have a working version of [R](https://www.r-project.org) and/or [Rstudio](https://posit.co/download/rstudio-desktop/) on your computer. 

If you have not used [the survival package](https://cran.r-project.org/web/packages/survival/index.html) in R before, we recommend familiarising yourself with the basic functions before the course. You can take a look of our [description of elementary survival analysis in R](survival.html) or use other introductory texts. 

The course will not assume any prior knowledge about causal inference, however having some familiarity with causal concepts would be beneficial. For example you could take a look at Chapters 1-3 and Chapter 17 in the book of Hernan and Robins, which can be freely downloaded here:  https://miguelhernan.org/whatifbook. 

The tutorial paper by Andersen et al. (2020) can also be recommended for general background on some fundamental concepts and methods in time-to-event analysis (https://doi.org/10.1002/sim.8757).

</br>
