---
title: "Program"
---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

---

All times are in CEST.

**Part 1: Introduction and estimation of the effects of point treatments on survival**

|Time                 |Topic                                                                                         |Tutor                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|11:00 - 11:45         |Lecture: Causal estimands for time-to-event outcomes and identification using observational data | Jon Michael Gran                       |                       |
|*11:45 - 12:00*        |*Short break* |                       |
|12:00 - 12:45        |Lecture: Estimating the effects of point treatments | Ruth Keogh                         |
|12:45 - 13:15        |R demo: Methods for point treatments | Jon Michael Gran                           |

|                 |                                                                                         |                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|*13:15 - 14:00*        |*Lunch* |                           |

**Part 2: Extensions to time-dependent treatment strategies**

|                 |                                                                                         |                   |
|:----------------------|:-----------------------------------------------------------------------------------------------|:-----------------------------|
|14:00 - 14:30        |Lecture: Extensions to time-dependent treatment strategies, and the challenge of time-dependent confounding |  Jon Michael Gran                        |                       |
|14:30 - 15:00        |Lecture: Further methods for time-dependent treatment strategies  | Ruth Keogh                         |
|*15:00 - 15:15*        |*Short break*  |                        |
|15:15 - 15:45        |R. demo: Methods for longitudinal treatment strategies  | Ruth Keogh                         |
|15:45 - 16:00        |Round up and questions  |                         |
</br>
